# Generated by Django 2.2 on 2020-03-31 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User', 'verbose_name_plural': 'User'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='voice_secrect',
            field=models.CharField(default='hello', max_length=50, verbose_name='voice secrect'),
        ),
    ]
