# Generated by Django 2.2 on 2020-04-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200331_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='voice_secrect',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='voice_secret',
            field=models.CharField(default='hello', max_length=50, verbose_name='voice secret'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(max_length=11, verbose_name='mobile number'),
        ),
    ]
