# Generated by Django 2.2 on 2020-03-17 21:23

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='added time')),
                ('name', models.CharField(max_length=50, verbose_name='course name')),
                ('desc', models.CharField(max_length=300, verbose_name='course description')),
                ('learn_times', models.IntegerField(default=0, verbose_name='length(mins)')),
                ('degree', models.CharField(choices=[('low', 'entry level'), ('mid', 'intermediated'), ('high', 'advanced')], max_length=20, verbose_name='difficulty')),
                ('students', models.IntegerField(default=0, verbose_name='students number')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='favorite number')),
                ('click_nums', models.IntegerField(default=0, verbose_name='clicks')),
                ('notice', models.CharField(default='', max_length=300, verbose_name='notice')),
                ('category', models.CharField(default='General Course', max_length=20, verbose_name='course category')),
                ('tag', models.CharField(default='', max_length=10, verbose_name='course tag')),
                ('youneed_know', models.CharField(default='', max_length=300, verbose_name='course requirements')),
                ('teacher_tell', models.CharField(default='', max_length=300, verbose_name='instructor notices')),
                ('is_classics', models.BooleanField(default=False, verbose_name='is recommanded')),
                ('detail', DjangoUeditor.models.UEditorField(default='', verbose_name='course details')),
                ('is_banner', models.BooleanField(default=False, verbose_name='is AD. banner')),
                ('image', models.ImageField(upload_to='courses/%Y/%m', verbose_name='course image')),
                ('course_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.CourseOrg', verbose_name='department')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.Teacher', verbose_name='instructor')),
            ],
            options={
                'verbose_name': 'Course Info',
                'verbose_name_plural': 'Course Info',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='added time')),
                ('name', models.CharField(max_length=100, verbose_name='chapter name')),
                ('learn_times', models.IntegerField(default=0, verbose_name='length(mins)')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='course')),
            ],
            options={
                'verbose_name': 'course chapter',
                'verbose_name_plural': 'course chapter',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='added time')),
                ('name', models.CharField(max_length=100, verbose_name='vide name')),
                ('learn_times', models.IntegerField(default=0, verbose_name='length(mins)')),
                ('url', models.CharField(max_length=1000, verbose_name='video url')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Lesson', verbose_name='chapter')),
            ],
            options={
                'verbose_name': 'video',
                'verbose_name_plural': 'video',
            },
        ),
        migrations.CreateModel(
            name='CourseTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='added time')),
                ('tag', models.CharField(max_length=100, verbose_name='course tag')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='course')),
            ],
            options={
                'verbose_name': 'course tag',
                'verbose_name_plural': 'course tag',
            },
        ),
        migrations.CreateModel(
            name='CourseResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='added time')),
                ('name', models.CharField(max_length=100, verbose_name='course resource name')),
                ('file', models.FileField(max_length=200, upload_to='course/resourse/%Y/%m', verbose_name='download path')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='course')),
            ],
            options={
                'verbose_name': 'course resource',
                'verbose_name_plural': 'course resource',
            },
        ),
        migrations.CreateModel(
            name='BannerCourse',
            fields=[
            ],
            options={
                'verbose_name': 'banner courses',
                'verbose_name_plural': 'banner courses',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('courses.course',),
        ),
    ]
