# Generated by Django 2.2 on 2020-03-17 21:23

import DjangoUeditor.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='added time')),
                ('name', models.CharField(max_length=20, verbose_name='campus name')),
                ('desc', models.CharField(max_length=200, verbose_name='description')),
            ],
            options={
                'verbose_name': 'campus',
                'verbose_name_plural': 'campus',
            },
        ),
        migrations.CreateModel(
            name='CourseOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='added time')),
                ('name', models.CharField(max_length=50, verbose_name='department name')),
                ('desc', DjangoUeditor.models.UEditorField(default='', verbose_name='description')),
                ('tag', models.CharField(default='general', max_length=10, verbose_name='deparment tag')),
                ('category', models.CharField(choices=[('under_grad', 'under graduate'), ('grad', 'graduated'), ('post_grad_cert', 'post graduated certificated')], default='general', max_length=4, verbose_name='program')),
                ('click_nums', models.IntegerField(default=0, verbose_name='click')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='favorite')),
                ('image', models.ImageField(upload_to='org/%Y/%m', verbose_name='logo')),
                ('address', models.CharField(max_length=150, verbose_name='department address')),
                ('students', models.IntegerField(default=0, verbose_name='students')),
                ('course_nums', models.IntegerField(default=0, verbose_name='courses')),
                ('is_auth', models.BooleanField(default=False, verbose_name='is_required')),
                ('is_gold', models.BooleanField(default=False, verbose_name='is_recommand')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.Campus', verbose_name='campus')),
            ],
            options={
                'verbose_name': 'Departments Info',
                'verbose_name_plural': 'Departments Info',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='added time')),
                ('name', models.CharField(max_length=50, verbose_name='instructor name')),
                ('work_years', models.IntegerField(default=0, verbose_name='work years')),
                ('work_company', models.CharField(max_length=50, verbose_name='company / school')),
                ('work_position', models.CharField(max_length=50, verbose_name='job title')),
                ('points', models.CharField(max_length=50, verbose_name='teaching characteristics')),
                ('click_nums', models.IntegerField(default=0, verbose_name='clicks')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='favorite number')),
                ('age', models.IntegerField(default=18, verbose_name='age')),
                ('image', models.ImageField(upload_to='teacher/%Y/%m', verbose_name='avatar')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.CourseOrg', verbose_name='department')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Instructor Info',
                'verbose_name_plural': 'Instructor Info',
            },
        ),
    ]
