# Generated by Django 2.2 on 2020-03-18 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseorg',
            options={'verbose_name': 'Department', 'verbose_name_plural': 'Department'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Instructor', 'verbose_name_plural': 'Instructor'},
        ),
        migrations.RemoveField(
            model_name='courseorg',
            name='image',
        ),
        migrations.AlterField(
            model_name='courseorg',
            name='category',
            field=models.CharField(choices=[('under_grad', 'under graduate'), ('grad', 'graduated'), ('post_grad_cert', 'post graduated certificated')], default='general', max_length=50, verbose_name='program'),
        ),
        migrations.AlterField(
            model_name='courseorg',
            name='desc',
            field=models.CharField(max_length=300, verbose_name='description'),
        ),
    ]
